# Generated by Django 5.2.1 on 2025-05-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_heritagesite_remove_travelexperience_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
