# Generated by Django 5.2.1 on 2025-05-17 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contribution_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='travelexperience',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
