# Generated by Django 5.2.1 on 2025-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_contribution_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelexperience',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelexperience',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
