# Generated by Django 5.1.4 on 2025-06-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ingredient_onlineshop_recipe_restaurant_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.food'),
        ),
    ]
