# Generated by Django 5.1.4 on 2025-06-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_food_alter_recipe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='recipes',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
