# Generated by Django 5.1.4 on 2025-06-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_restaurant_recipes_delete_recipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('historical_essence', models.TextField(blank=True, null=True)),
                ('carbohydrate', models.TextField(blank=True, null=True)),
                ('protein', models.TextField(blank=True, null=True)),
                ('fat', models.TextField(blank=True, null=True)),
                ('calories', models.TextField(blank=True, null=True)),
                ('tutorial_video_url', models.URLField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='img')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('ingredient_list', models.ManyToManyField(related_name='recipes', to='main.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('maps_link', models.URLField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('recipes', models.ManyToManyField(related_name='restaurants', to='main.recipe')),
            ],
        ),
    ]
