# Generated by Django 5.1.4 on 2025-06-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_recipe_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
