# Generated by Django 5.1.4 on 2025-06-12 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_food_remove_recipe_id_alter_recipe_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historical_Significance',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.food')),
                ('history', models.TextField(blank=True, null=True)),
                ('cultural_significance', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
