# Generated by Django 5.1.4 on 2025-06-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_image1_recipe_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tutorial_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
