# Generated by Django 5.1.4 on 2025-06-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_recipe_tutorial_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tutorial_video_url',
        ),
        migrations.AddField(
            model_name='food',
            name='tutorial_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
