# Generated by Django 5.1.4 on 2025-06-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_recipe_tutorial_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineBuying',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.food')),
                ('product_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
