# Generated by Django 5.1.4 on 2025-06-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_onlinebuying'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='recipes',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food',
            field=models.ManyToManyField(related_name='restaurants', to='main.food'),
        ),
    ]
