# Generated by Django 5.1.4 on 2025-06-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_restaurant_recipes_restaurant_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinebuying',
            name='name',
        ),
        migrations.AddField(
            model_name='onlinebuying',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buying_links', to='main.food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinebuying',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
