# Generated by Django 5.1.4 on 2025-06-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_onlinebuying_name_onlinebuying_food_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinebuying',
            old_name='food',
            new_name='name',
        ),
    ]
