# Generated by Django 5.1.4 on 2025-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_food_onlinebuying_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='img')),
                ('shortdescription', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('cultural_significance', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
