# Generated by Django 5.1.4 on 2025-06-15 12:48

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_accomodation_link_accomodation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguides',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourguides',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='NP'),
        ),
    ]
